// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_AqHe8kAAbhVvFYRNxAX4rv3_VLVRfDw',
    appId: '1:987714075267:web:1f3b7c8a3b9051e2be79b6',
    messagingSenderId: '987714075267',
    projectId: 'taskyapp-167da',
    authDomain: 'taskyapp-167da.firebaseapp.com',
    storageBucket: 'taskyapp-167da.firebasestorage.app',
    measurementId: 'G-M69CMNY6ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrspVVD8h9AipQv-fql4qOuFHUQ1VdSiU',
    appId: '1:987714075267:android:1bed5751a881f292be79b6',
    messagingSenderId: '987714075267',
    projectId: 'taskyapp-167da',
    storageBucket: 'taskyapp-167da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWcvDSvoDH3Fs6J2HiafWi3oOfda3_L6o',
    appId: '1:987714075267:ios:913ab279ff70cd0abe79b6',
    messagingSenderId: '987714075267',
    projectId: 'taskyapp-167da',
    storageBucket: 'taskyapp-167da.firebasestorage.app',
    iosBundleId: 'com.example.taskyapp',
  );
}